# Generated by Django 6.0.7 on 2026-08-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0006_userprofile_display_name_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='handle',
        ),
    ]
