# Generated by Django 6.0.7 on 2026-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0003_message_image_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
